### ISSUE TITLE
Implement the `/crawl` API

### ISSUE THREAD

**Issue by mateimicu** [micumatei/asciipic#61]
This api will post a job that will crawl some website ( using the API or not ) for the specific images.
A limit will be imposed ( let's say 50 images max ).

The API will post a job ( maybe return the job-id). When we query for crawl request we should see if it's job and and use that to determine if the job is `pending`, `doing`, `done`
Parameters for the crawl api :  
- site (facebook, instagram ... etc )
- tag ( multiple )
- post_date
- width
- height

**Comment by AlexandruTudose** [comment]
Done
