### ISSUE TITLE
Implement the Flicker crawl job.

### ISSUE THREAD

**Issue by mateimicu** [micumatei/asciipic#66]
Use the https://www.flickr.com/services/api/ if possible and implement the crawl job using the base job implemented https://github.com/micumatei/asciipic/issues/58 .
If the API is not public ( meaning that the limits are too low, or we can't acces real data - just mocked one ) we could use https://scrapy.org/ to actually scrape the website ( this method is just as a last resort )

**Comment by AlexandruTudose** [comment]
Done. Flickr API doesn't have support to search by width and height. I tried implementing blind search but due to the fact that we have limited requests per hour, it wasn't feasible to do so.
